name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Set environment variables for production
        run: |
          echo "VITE_BACKEND_URL=https://merror-backend.onrender.com" >> .env.production
          echo "VITE_WEBSOCKET_URL=wss://merror-backend.onrender.com" >> .env.production

      - name: Build project
        run: yarn build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.9
        with:
          publish-dir: ./dist
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
